export let movies = [
{
"id": 1,
"title": "Bitelchús",
"year": "1988",
"runtime": "92",
"genres": ["Comedy","Fantasy"],
"director": "Tim Burton",
"actors": "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page",
"plot": "Una pareja de fantasmas recientemente fallecidos contrata los servicios de un \"bio-exorcista\" para desalojar a los nuevos y molestos propietarios de su casa.",
"posterUrl": "https://image.tmdb.org/t/p/w500/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg"
},
{
"id": 2,
"title": "El Cotton Club",
"year": "1984",
"runtime": "127",
"genres": ["Crime","Drama","Music"],
"director": "Francis Ford Coppola",
"actors": "Richard Gere, Gregory Hines, Diane Lane, Lonette McKee",
"plot": "El Cotton Club fue un famoso club nocturno en Harlem. La historia sigue a quienes lo visitaban y lo dirigían, acompañada por el jazz que lo hizo tan famoso.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU5ODAyNzA4OV5BMl5BanBnXkFtZTcwNzYwNTIzNA@@._V1_SX300.jpg"
},
{
"id": 3,
"title": "Cadena perpetua",
"year": "1994",
"runtime": "142",
"genres": ["Crime","Drama"],
"director": "Frank Darabont",
"actors": "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
"plot": "Dos hombres encarcelados forjan una amistad durante años, encontrando consuelo y redención a través de actos de decencia.",
"posterUrl": "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg"
},
{
"id": 4,
"title": "Cocodrilo Dundee",
"year": "1986",
"runtime": "97",
"genres": ["Adventure","Comedy"],
"director": "Peter Faiman",
"actors": "Paul Hogan, Linda Kozlowski, John Meillon, David Gulpilil",
"plot": "Una reportera estadounidense viaja al interior de Australia para conocer a un excéntrico cazador de cocodrilos y lo invita a Nueva York.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0MTU1MTg4NF5BMl5BanBnXkFtZTgwMDgzNzYxMTE@._V1_SX300.jpg"
},
{
"id": 5,
"title": "Operación Valquiria",
"year": "2008",
"runtime": "121",
"genres": ["Drama","History","Thriller"],
"director": "Bryan Singer",
"actors": "Tom Cruise, Kenneth Branagh, Bill Nighy, Tom Wilkinson",
"plot": "Dramatización del complot del 20 de julio para asesinar a Hitler durante la Segunda Guerra Mundial.",
"posterUrl": "https://m.media-amazon.com/images/I/81VWkOqQn0L._AC_UF1000,1000_QL80_.jpg"
},
{
"id": 6,
"title": "Ratatouille",
"year": "2007",
"runtime": "111",
"genres": ["Animation","Comedy","Family"],
"director": "Brad Bird, Jan Pinkava",
"actors": "Patton Oswalt, Ian Holm, Lou Romano, Brian Dennehy",
"plot": "Una rata con talento para la cocina forma una alianza inesperada con un joven trabajador en un restaurante famoso.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_SX300.jpg"
},
{
"id": 7,
"title": "Ciudad de Dios",
"year": "2002",
"runtime": "130",
"genres": ["Crime","Drama"],
"director": "Fernando Meirelles, Kátia Lund",
"actors": "Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen, Douglas Silva",
"plot": "Dos jóvenes que crecen en un barrio violento de Río de Janeiro toman caminos distintos: uno se convierte en fotógrafo y el otro en narcotraficante.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4ODQ3ODkzNV5BMl5BanBnXkFtZTYwOTc4NDI3._V1_SX300.jpg"
},
{
"id": 8,
"title": "Memento",
"year": "2000",
"runtime": "113",
"genres": ["Mystery","Thriller"],
"director": "Christopher Nolan",
"actors": "Guy Pearce, Carrie-Anne Moss, Joe Pantoliano, Mark Boone Junior",
"plot": "Un hombre busca al asesino de su esposa mientras lucha contra su pérdida de memoria a corto plazo.",
"posterUrl": "https://m.media-amazon.com/images/I/91OJsdscU9L._SY522_.jpg"
},
{
"id": 9,
"title": "Intocable",
"year": "2011",
"runtime": "112",
"genres": ["Biography","Comedy","Drama"],
"director": "Olivier Nakache, Eric Toledano",
"actors": "François Cluzet, Omar Sy, Anne Le Ny, Audrey Fleurot",
"plot": "Tras quedar tetrapléjico en un accidente, un aristócrata contrata a un joven de los suburbios como cuidador.",
"posterUrl": "https://m.media-amazon.com/images/I/81U+rm4qtwL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 10,
"title": "Cuestión de estrellas",
"year": "2007",
"runtime": "127",
"genres": ["Adventure","Family","Fantasy"],
"director": "Matthew Vaughn",
"actors": "Ian McKellen, Bimbo Hart, Alastair MacIntosh, David Kelly",
"plot": "Un joven promete a su amada recuperar una estrella caída adentrándose en un reino mágico.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjkyMTE1OTYwNF5BMl5BanBnXkFtZTcwMDIxODYzMw@@._V1_SX300.jpg"
},
{
"id": 11,
"title": "Apocalypto",
"year": "2006",
"runtime": "139",
"genres": ["Action","Adventure","Drama"],
"director": "Mel Gibson",
"actors": "Rudy Youngblood, Dalia Hernández, Jonathan Brewer, Morris Birdyellowhead",
"plot": "Un joven capturado para sacrificio intenta escapar para salvar su vida y la de su familia.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTM1NjYyNTY5OV5BMl5BanBnXkFtZTcwMjgwNTMzMQ@@._V1_SX300.jpg"
},
{
"id": 12,
"title": "Taxi Driver",
"year": "1976",
"runtime": "113",
"genres": ["Crime","Drama"],
"director": "Martin Scorsese",
"actors": "Diahnne Abbott, Frank Adu, Victor Argo, Gino Ardito",
"plot": "Un veterano inestable de Vietnam trabaja como taxista nocturno en Nueva York, donde su mente se deteriora peligrosamente.",
"posterUrl": "https://image.tmdb.org/t/p/w500/ekstpH614fwDX8DUln1a2Opz0N8.jpg"
},
{
"id": 13,
"title": "No es país para viejos",
"year": "2007",
"runtime": "122",
"genres": ["Crime","Drama","Thriller"],
"director": "Ethan Coen, Joel Coen",
"actors": "Tommy Lee Jones, Javier Bardem, Josh Brolin, Woody Harrelson",
"plot": "La violencia estalla cuando un cazador encuentra millones de dólares tras un negocio de drogas fallido.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg"
},
{
"id": 14,
"title": "El planeta 51",
"year": "2009",
"runtime": "91",
"genres": ["Animation","Adventure","Comedy"],
"director": "Jorge Blanco, Javier Abad, Marcos Martínez",
"actors": "Jessica Biel, John Cleese, Gary Oldman, Dwayne Johnson",
"plot": "Un astronauta invade accidentalmente un planeta habitado y debe regresar a su nave antes de que despegue sin él.",
"posterUrl": "https://m.media-amazon.com/images/I/91HKM7sO9gL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 15,
"title": "Looper",
"year": "2012",
"runtime": "119",
"genres": ["Action","Crime","Drama"],
"director": "Rian Johnson",
"actors": "Joseph Gordon-Levitt, Bruce Willis, Emily Blunt, Paul Dano",
"plot": "Un sicario descubre que debe matar a su propio yo del futuro.",
"posterUrl": "https://pics.filmaffinity.com/Looper-874353819-mmed.jpg"
},
{
"id": 16,
"title": "La novia cadáver",
"year": "2005",
"runtime": "77",
"genres": ["Animation","Drama","Family"],
"director": "Tim Burton, Mike Johnson",
"actors": "Johnny Depp, Helena Bonham Carter, Emily Watson, Tracey Ullman",
"plot": "Un novio tímido practica sus votos y accidentalmente despierta a una novia cadáver que cree que se ha casado con ella.",
"posterUrl": "https://image.tmdb.org/t/p/w500/isb2Qow76GpqYmsSyfdMfsYAjts.jpg"
},
{
"id": 17,
"title": "El tercer hombre",
"year": "1949",
"runtime": "93",
"genres": ["Film-Noir","Mystery","Thriller"],
"director": "Carol Reed",
"actors": "Joseph Cotten, Alida Valli, Orson Welles, Trevor Howard",
"plot": "Un escritor investiga la misteriosa muerte de un viejo amigo en la Viena de posguerra.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMwNzMzMTQ0Ml5BMl5BanBnXkFtZTgwNjExMzUwNjE@._V1_SX300.jpg"
},
{
"id": 18,
"title": "La playa",
"year": "2000",
"runtime": "119",
"genres": ["Adventure","Drama","Romance"],
"director": "Danny Boyle",
"actors": "Leonardo DiCaprio, Daniel York, Patcharawan Patarakijjanon, Virginie Ledoyen",
"plot": "Un joven viaja a Tailandia en busca de una playa paradisíaca secreta.",
"posterUrl": "https://upload.wikimedia.org/wikipedia/en/b/bc/The_Beach_film.jpg"
},
{
"id": 19,
"title": "Scarface",
"year": "1983",
"runtime": "170",
"genres": ["Crime","Drama"],
"director": "Brian De Palma",
"actors": "Al Pacino, Steven Bauer, Michelle Pfeiffer, Mary Elizabeth Mastrantonio",
"plot": "Un inmigrante cubano asciende en el mundo del narcotráfico en Miami hasta que la ambición lo destruye.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAzOTM4MzEwNl5BMl5BanBnXkFtZTgwMzU1OTc1MDE@._V1_SX300.jpg"
},
{
"id": 20,
"title": "Sid y Nancy",
"year": "1986",
"runtime": "112",
"genres": ["Biography","Drama","Music"],
"director": "Alex Cox",
"actors": "Gary Oldman, Chloe Webb, David Hayman, Debby Bishop",
"plot": "Historia de la relación autodestructiva entre Sid Vicious y Nancy Spungen tras la caída de los Sex Pistols.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjExNjA5NzY4M15BMl5BanBnXkFtZTcwNjQ2NzI5NA@@._V1_SX300.jpg"
},
{
"id": 21,
"title": "El cisne negro",
"year": "2010",
"runtime": "108",
"genres": ["Drama","Thriller"],
"director": "Darren Aronofsky",
"actors": "Natalie Portman, Mila Kunis, Vincent Cassel, Barbara Hershey",
"plot": "Una bailarina obsesionada consigue el papel principal en \"El lago de los cisnes\", pero su búsqueda de perfección comienza a destruir su mente.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg"
},
{
"id": 22,
"title": "El origen",
"year": "2010",
"runtime": "148",
"genres": ["Action","Adventure","Sci-Fi"],
"director": "Christopher Nolan",
"actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy",
"plot": "Un ladrón que roba secretos a través de los sueños recibe la misión inversa: implantar una idea en la mente de un CEO.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg"
},
{
"id": 23,
"title": "El cazador",
"year": "1978",
"runtime": "183",
"genres": ["Drama","War"],
"director": "Michael Cimino",
"actors": "Robert De Niro, John Cazale, John Savage, Christopher Walken",
"plot": "Un análisis profundo del impacto devastador de la Guerra de Vietnam en un grupo de amigos de un pequeño pueblo industrial.",
"posterUrl": "https://m.media-amazon.com/images/I/91aIAXL3wZL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 24,
"title": "Persiguiendo a Amy",
"year": "1997",
"runtime": "113",
"genres": ["Comedy","Drama","Romance"],
"director": "Kevin Smith",
"actors": "Ethan Suplee, Ben Affleck, Scott Mosier, Jason Lee",
"plot": "Un dibujante de cómics se enamora de una artista que resulta ser lesbiana, poniendo en riesgo su amistad y sus propias inseguridades.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZDM3MTg2MGUtZDM0MC00NzMwLWE5NjItOWFjNjA2M2I4YzgxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"
},
{
"id": 25,
"title": "Django desencadenado",
"year": "2012",
"runtime": "165",
"genres": ["Drama","Western"],
"director": "Quentin Tarantino",
"actors": "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington",
"plot": "Un esclavo liberado se une a un cazarrecompensas alemán para rescatar a su esposa de un brutal terrateniente.",
"posterUrl": "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg"
},
{
"id": 26,
"title": "Blade Runner",
"year": "1982",
"runtime": "117",
"genres": ["Sci-Fi","Thriller"],
"director": "Ridley Scott",
"actors": "Harrison Ford, Rutger Hauer, Sean Young",
"plot": "Un blade runner debe retirar a unos replicantes rebeldes en un futuro distópico.",
"posterUrl": "https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg"
},
{
"id": 27,
"title": "American Beauty",
"year": "1999",
"runtime": "122",
"genres": ["Drama","Romance"],
"director": "Sam Mendes",
"actors": "Kevin Spacey, Annette Bening, Thora Birch, Wes Bentley",
"plot": "Un padre de familia atraviesa una crisis de mediana edad tras obsesionarse con la amiga de su hija.",
"posterUrl": "https://m.media-amazon.com/images/I/91gPNId1OcL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 28,
"title": "Snatch",
"year": "2000",
"runtime": "102",
"genres": ["Comedy","Crime"],
"director": "Guy Ritchie",
"actors": "Benicio Del Toro, Dennis Farina, Vinnie Jones, Brad Pitt",
"plot": "Promotores corruptos, gánsteres y ladrones torpes se cruzan por un diamante robado de gran valor.",
"posterUrl": "https://image.tmdb.org/t/p/w500/56mOJth6DJ6JhgoE2jtpilVqJO.jpg"
},
{
"id": 29,
"title": "Expreso de medianoche",
"year": "1978",
"runtime": "121",
"genres": ["Crime","Drama","Thriller"],
"director": "Alan Parker",
"actors": "Brad Davis, Irene Miracle, Bo Hopkins, Paolo Bonacelli",
"plot": "Un estudiante estadounidense es encarcelado en Turquía tras intentar sacar drogas del país.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQyMDA5MzkyOF5BMl5BanBnXkFtZTgwOTYwNTcxMTE@._V1_SX300.jpg"
},
{
"id": 30,
"title": "Pulp Fiction",
"year": "1994",
"runtime": "154",
"genres": ["Crime","Drama"],
"director": "Quentin Tarantino",
"actors": "Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta",
"plot": "Las vidas de varios criminales se entrelazan en historias de violencia y redención.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SX300.jpg"
},
{
"id": 31,
"title": "Lock & Stock",
"year": "1998",
"runtime": "107",
"genres": ["Comedy","Crime"],
"director": "Guy Ritchie",
"actors": "Jason Flemyng, Dexter Fletcher, Nick Moran, Jason Statham",
"plot": "Una partida de cartas fraudulenta desencadena una cadena de caos criminal en Londres.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTAyN2JmZmEtNjAyMy00NzYwLThmY2MtYWQ3OGNhNjExMmM4XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg"
},
{
"id": 32,
"title": "La trama",
"year": "2006",
"runtime": "110",
"genres": ["Crime","Drama","Mystery"],
"director": "Paul McGuigan",
"actors": "Josh Hartnett, Bruce Willis, Lucy Liu, Morgan Freeman",
"plot": "Un caso de identidad equivocada coloca a Slevin en medio de una guerra entre dos jefes criminales rivales.",
"posterUrl": "https://m.media-amazon.com/images/I/81YRa0Z6CvL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 33,
"title": "La ventana indiscreta",
"year": "1954",
"runtime": "112",
"genres": ["Mystery","Thriller"],
"director": "Alfred Hitchcock",
"actors": "James Stewart, Grace Kelly, Wendell Corey, Thelma Ritter",
"plot": "Un fotógrafo en silla de ruedas cree haber presenciado un asesinato desde la ventana de su apartamento.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"
},
{
"id": 34,
"title": "El laberinto del fauno",
"year": "2006",
"runtime": "118",
"genres": ["Drama","Fantasy","War"],
"director": "Guillermo del Toro",
"actors": "Ivana Baquero, Sergi López, Maribel Verdú, Doug Jones",
"plot": "En la España franquista de 1944, una niña escapa a un mundo fantástico mientras su padrastro militar impone el terror.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BOTc1NTAxMWItMWFlNy00MmU2LTkwMTMtNzMwOTg5OTQ5YTFiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
},
{
"id": 35,
"title": "La isla siniestra",
"year": "2010",
"runtime": "138",
"genres": ["Mystery","Thriller"],
"director": "Martin Scorsese",
"actors": "Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley, Max von Sydow",
"plot": "Un agente federal investiga la desaparición de una paciente en un hospital psiquiátrico aislado.",
"posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxMTIyNzMxMV5BMl5BanBnXkFtZTcwOTc4OTI3Mg@@._V1_SX300.jpg"
},
{
"id": 36,
"title": "Reservoir Dogs",
"year": "1992",
"runtime": "99",
"genres": ["Crime","Drama","Thriller"],
"director": "Quentin Tarantino",
"actors": "Harvey Keitel, Tim Roth, Michael Madsen, Chris Penn",
"plot": "Tras un robo fallido, un grupo de criminales sospecha que uno de ellos es un infiltrado.",
"posterUrl": "https://m.media-amazon.com/images/I/91fyNVbnvmL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 37,
"title": "El resplandor",
"year": "1980",
"runtime": "146",
"genres": ["Drama","Horror"],
"director": "Stanley Kubrick",
"actors": "Jack Nicholson, Shelley Duvall, Danny Lloyd, Scatman Crothers",
"plot": "Una familia se instala en un hotel aislado donde una presencia maligna empuja al padre hacia la locura.",
"posterUrl": "https://upload.wikimedia.org/wikipedia/en/1/1d/The_Shining_%281980%29_U.K._release_poster_-_The_tide_of_terror_that_swept_America_IS_HERE.jpg"
},
{
"id": 38,
"title": "Medianoche en París",
"year": "2011",
"runtime": "94",
"genres": ["Comedy","Fantasy","Romance"],
"director": "Woody Allen",
"actors": "Owen Wilson, Rachel McAdams, Kurt Fuller, Mimi Kennedy",
"plot": "Un escritor viaja misteriosamente cada medianoche al París de los años 20.",
"posterUrl": "https://m.media-amazon.com/images/I/911GtQjVe3L._AC_UF1000,1000_QL80_.jpg"
},
{
"id": 39,
"title": "Los miserables",
"year": "2012",
"runtime": "158",
"genres": ["Drama","Musical","Romance"],
"director": "Tom Hooper",
"actors": "Hugh Jackman, Russell Crowe, Anne Hathaway, Amanda Seyfried",
"plot": "En la Francia del siglo XIX, Jean Valjean intenta rehacer su vida mientras es perseguido por el inspector Javert.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BNDUzMDcyZjMtM2M5NC00NGNkLWIxN2YtOTEwODMxNTEzZDU1XkEyXkFqcGc@._V1_.jpg"
},
{
"id": 40,
"title": "L.A. Confidencial",
"year": "1997",
"runtime": "138",
"genres": ["Crime","Drama","Mystery"],
"director": "Curtis Hanson",
"actors": "Kevin Spacey, Russell Crowe, Guy Pearce, James Cromwell",
"plot": "Tres policías con métodos muy distintos investigan una serie de asesinatos en el Los Ángeles de los años 50.",
"posterUrl": "https://m.media-amazon.com/images/I/81bldr+0gzL.jpg"
},
{
"id": 41,
"title": "Infiltrados",
"year": "2006",
"runtime": "151",
"genres": ["Crime","Drama","Thriller"],
"director": "Martin Scorsese",
"actors": "Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg",
"plot": "Un policía infiltrado en la mafia y un criminal infiltrado en la policía intentan descubrir la identidad del otro.",
"posterUrl": "https://m.media-amazon.com/images/I/91RWJkPah+L._AC_UF894,1000_QL80_.jpg"
},
{
"id": 42,
"title": "Gladiator",
"year": "2000",
"runtime": "155",
"genres": ["Action","Adventure","Drama"],
"director": "Ridley Scott",
"actors": "Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed",
"plot": "Un general romano traicionado busca venganza convirtiéndose en gladiador.",
"posterUrl": "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg"
},
{
"id": 43,
"title": "El caballero oscuro",
"year": "2008",
"runtime": "152",
"genres": ["Action","Crime","Drama"],
"director": "Christopher Nolan",
"actors": "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
"plot": "Batman se enfrenta al Joker, un criminal que siembra el caos en Gotham.",
"posterUrl": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg"
},
{
"id": 44,
"title": "El club de la lucha",
"year": "1999",
"runtime": "139",
"genres": ["Drama"],
"director": "David Fincher",
"actors": "Brad Pitt, Edward Norton, Helena Bonham Carter, Meat Loaf",
"plot": "Un hombre insomne crea un club secreto de lucha que evoluciona hacia algo mucho más peligroso.",
"posterUrl": "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg"
},
{
"id": 45,
"title": "Forrest Gump",
"year": "1994",
"runtime": "142",
"genres": ["Drama","Romance"],
"director": "Robert Zemeckis",
"actors": "Tom Hanks, Robin Wright, Gary Sinise, Sally Field",
"plot": "Un hombre con discapacidad intelectual vive momentos clave de la historia de EE.UU. sin perder su inocencia.",
"posterUrl": "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg"
},
{
"id": 46,
"title": "Matrix",
"year": "1999",
"runtime": "136",
"genres": ["Action","Sci-Fi"],
"director": "Lana Wachowski, Lilly Wachowski",
"actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
"plot": "Un hacker descubre que la realidad es una simulación creada por máquinas.",
"posterUrl": "https://image.tmdb.org/t/p/w500/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg"
},
{
"id": 47,
"title": "Se7en",
"year": "1995",
"runtime": "127",
"genres": ["Crime","Drama","Mystery"],
"director": "David Fincher",
"actors": "Morgan Freeman, Brad Pitt, Kevin Spacey, Gwyneth Paltrow",
"plot": "Dos detectives persiguen a un asesino que basa sus crímenes en los siete pecados capitales.",
"posterUrl": "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg"
},
{
"id": 48,
"title": "Interstellar",
"year": "2014",
"runtime": "169",
"genres": ["Adventure","Drama","Sci-Fi"],
"director": "Christopher Nolan",
"actors": "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine",
"plot": "Un grupo de exploradores viaja a través de un agujero de gusano para salvar a la humanidad.",
"posterUrl": "https://m.media-amazon.com/images/I/91vIHsL-zjL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 49,
"title": "El padrino",
"year": "1972",
"runtime": "175",
"genres": ["Crime","Drama"],
"director": "Francis Ford Coppola",
"actors": "Marlon Brando, Al Pacino, James Caan, Diane Keaton",
"plot": "La historia de la familia mafiosa Corleone y la transformación de Michael en su nuevo líder.",
"posterUrl": "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg"
},
{
"id": 50,
"title": "El padrino. Parte II",
"year": "1974",
"runtime": "202",
"genres": ["Crime","Drama"],
"director": "Francis Ford Coppola",
"actors": "Al Pacino, Robert De Niro, Robert Duvall, Diane Keaton",
"plot": "La vida temprana de Vito Corleone se entrelaza con el reinado de su hijo Michael.",
"posterUrl": "https://image.tmdb.org/t/p/w500/amvmeQWheahG3StKwIE1f7jRnkZ.jpg"
},
{
"id": 51,
"title": "Uno de los nuestros",
"year": "1990",
"runtime": "146",
"genres": ["Crime","Drama"],
"director": "Martin Scorsese",
"actors": "Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco",
"plot": "La vida de un mafioso desde su juventud hasta su caída.",
"posterUrl": "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg"
},
{
"id": 52,
"title": "Braveheart",
"year": "1995",
"runtime": "178",
"genres": ["Biography","Drama","History"],
"director": "Mel Gibson",
"actors": "Mel Gibson, Sophie Marceau, Patrick McGoohan, Angus Macfadyen",
"plot": "William Wallace lidera la rebelión escocesa contra la opresión inglesa.",
"posterUrl": "https://image.tmdb.org/t/p/w500/or1gBugydmjToAEq7OZY0owwFk.jpg"
},
{
"id": 53,
"title": "Titanic",
"year": "1997",
"runtime": "195",
"genres": ["Drama","Romance"],
"director": "James Cameron",
"actors": "Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates",
"plot": "Una historia de amor surge a bordo del RMS Titanic antes de su trágico hundimiento.",
"posterUrl": "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg"
},
{
"id": 54,
"title": "Avatar",
"year": "2009",
"runtime": "162",
"genres": ["Action","Adventure","Fantasy"],
"director": "James Cameron",
"actors": "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
"plot": "Un marine parapléjico se integra en la cultura Na'vi en el planeta Pandora.",
"posterUrl": "https://image.tmdb.org/t/p/w500/6EiRUJpuoeQPghrs3YNktfnqOVh.jpg"
},
{
"id": 55,
"title": "El señor de los anillos: La comunidad del anillo",
"year": "2001",
"runtime": "178",
"genres": ["Adventure","Fantasy"],
"director": "Peter Jackson",
"actors": "Elijah Wood, Ian McKellen, Viggo Mortensen, Sean Astin",
"plot": "Un hobbit emprende un viaje para destruir un anillo que amenaza la Tierra Media.",
"posterUrl": "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg"
},
{
"id": 56,
"title": "El señor de los anillos: Las dos torres",
"year": "2002",
"runtime": "179",
"genres": ["Adventure","Fantasy"],
"director": "Peter Jackson",
"actors": "Elijah Wood, Ian McKellen, Viggo Mortensen, Orlando Bloom",
"plot": "La Comunidad se divide mientras continúa la lucha contra Sauron.",
"posterUrl": "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg"
},
{
"id": 57,
"title": "El señor de los anillos: El retorno del rey",
"year": "2003",
"runtime": "201",
"genres": ["Adventure","Fantasy"],
"director": "Peter Jackson",
"actors": "Elijah Wood, Viggo Mortensen, Ian McKellen, Orlando Bloom",
"plot": "La batalla final por la Tierra Media decide el destino del anillo.",
"posterUrl": "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg"
},
{
"id": 58,
"title": "El truco final",
"year": "2006",
"runtime": "130",
"genres": ["Drama","Mystery","Sci-Fi"],
"director": "Christopher Nolan",
"actors": "Christian Bale, Hugh Jackman, Scarlett Johansson, Michael Caine",
"plot": "Dos magos rivales llevan su obsesión por superarse al límite.",
"posterUrl": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Prestige_poster.jpg/250px-Prestige_poster.jpg"
},
{
"id": 59,
"title": "Whiplash",
"year": "2014",
"runtime": "106",
"genres": ["Drama","Music"],
"director": "Damien Chazelle",
"actors": "Miles Teller, J.K. Simmons, Paul Reiser, Melissa Benoist",
"plot": "Un joven baterista es llevado al límite por su exigente instructor.",
"posterUrl": "https://image.tmdb.org/t/p/w500/oPxnRhyAIzJKGUEdSiwTJQBa3NM.jpg"
},
{
"id": 60,
"title": "La red social",
"year": "2010",
"runtime": "120",
"genres": ["Biography","Drama"],
"director": "David Fincher",
"actors": "Jesse Eisenberg, Andrew Garfield, Justin Timberlake, Rooney Mara",
"plot": "La creación de Facebook y los conflictos legales que siguieron.",
"posterUrl": "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg"
},
{
"id": 61,
"title": "El pianista",
"year": "2002",
"runtime": "150",
"genres": ["Biography","Drama","War"],
"director": "Roman Polanski",
"actors": "Adrien Brody, Thomas Kretschmann, Frank Finlay, Maureen Lipman",
"plot": "Un pianista judío lucha por sobrevivir a la destrucción del gueto de Varsovia durante la Segunda Guerra Mundial.",
"posterUrl": "https://image.tmdb.org/t/p/w500/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg"
},
{
"id": 62,
"title": "La milla verde",
"year": "1999",
"runtime": "189",
"genres": ["Crime","Drama","Fantasy"],
"director": "Frank Darabont",
"actors": "Tom Hanks, Michael Clarke Duncan, David Morse, Bonnie Hunt",
"plot": "Un funcionario de prisión descubre que un condenado a muerte posee un don sobrenatural.",
"posterUrl": "https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg"
},
{
"id": 63,
"title": "El silencio de los corderos",
"year": "1991",
"runtime": "118",
"genres": ["Crime","Drama","Thriller"],
"director": "Jonathan Demme",
"actors": "Jodie Foster, Anthony Hopkins, Scott Glenn, Ted Levine",
"plot": "Una joven agente del FBI busca la ayuda de un asesino encarcelado para atrapar a otro criminal.",
"posterUrl": "https://image.tmdb.org/t/p/w500/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg"
},
{
"id": 64,
"title": "Salvar al soldado Ryan",
"year": "1998",
"runtime": "169",
"genres": ["Drama","War"],
"director": "Steven Spielberg",
"actors": "Tom Hanks, Matt Damon, Tom Sizemore, Edward Burns",
"plot": "Un grupo de soldados arriesga sus vidas para rescatar a un paracaidista tras el desembarco de Normandía.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
},
{
"id": 65,
"title": "Sospechosos habituales",
"year": "1995",
"runtime": "106",
"genres": ["Crime","Mystery","Thriller"],
"director": "Bryan Singer",
"actors": "Kevin Spacey, Gabriel Byrne, Chazz Palminteri, Benicio Del Toro",
"plot": "Un único superviviente relata los hechos que condujeron a un misterioso y mortal enfrentamiento.",
"posterUrl": "https://image.tmdb.org/t/p/w500/bUPmtQzrRhzqYySeiMpv7GurAfm.jpg"
},
{
"id": 66,
"title": "American History X",
"year": "1998",
"runtime": "119",
"genres": ["Crime","Drama"],
"director": "Tony Kaye",
"actors": "Edward Norton, Edward Furlong, Beverly D'Angelo, Jennifer Lien",
"plot": "Un ex neonazi intenta evitar que su hermano menor siga el mismo camino de odio.",
"posterUrl": "https://m.media-amazon.com/images/I/81gFsrQDw7L._AC_UF894,1000_QL80_.jpg"
},
{
"id": 67,
"title": "El rey león",
"year": "1994",
"runtime": "88",
"genres": ["Animation","Adventure","Drama"],
"director": "Roger Allers, Rob Minkoff",
"actors": "Matthew Broderick, Jeremy Irons, James Earl Jones, Whoopi Goldberg",
"plot": "Un joven león debe aceptar su destino como rey tras la muerte de su padre.",
"posterUrl": "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg"
},
{
"id": 68,
"title": "La llegada",
"year": "2016",
"runtime": "116",
"genres": ["Drama","Sci-Fi","Mystery"],
"director": "Denis Villeneuve",
"actors": "Amy Adams, Jeremy Renner, Forest Whitaker",
"plot": "Una lingüista intenta comunicarse con extraterrestres tras su llegada a la Tierra.",
"posterUrl": "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg"
},
{
"id": 69,
"title": "La cosa",
"year": "1982",
"runtime": "109",
"genres": ["Horror","Sci-Fi","Mystery"],
"director": "John Carpenter",
"actors": "Kurt Russell, Wilford Brimley, Keith David",
"plot": "Un grupo de científicos en la Antártida enfrenta una criatura que puede imitar cualquier forma de vida.",
"posterUrl": "https://image.tmdb.org/t/p/w500/tzGY49kseSE9QAKk47uuDGwnSCu.jpg"
},
{
"id": 70,
"title": "Regreso al futuro",
"year": "1985",
"runtime": "116",
"genres": ["Adventure","Comedy","Sci-Fi"],
"director": "Robert Zemeckis",
"actors": "Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover",
"plot": "Un adolescente viaja accidentalmente al pasado y debe asegurar que sus padres se enamoren.",
"posterUrl": "https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg"
},
{
"id": 71,
"title": "Pozos de ambición",
"year": "2007",
"runtime": "158",
"genres": ["Drama"],
"director": "Paul Thomas Anderson",
"actors": "Daniel Day-Lewis, Paul Dano, Ciarán Hinds",
"plot": "Un ambicioso empresario petrolero manipula y destruye todo a su paso en su obsesión por el poder y la riqueza.",
"posterUrl": "https://image.tmdb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6U.jpg"
},
{
"id": 72,
"title": "El lobo de Wall Street",
"year": "2013",
"runtime": "180",
"genres": ["Biography","Comedy","Crime"],
"director": "Martin Scorsese",
"actors": "Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey",
"plot": "El ascenso y caída de un ambicioso corredor de bolsa envuelto en fraude y excesos.",
"posterUrl": "https://image.tmdb.org/t/p/w500/sOxr33wnRuKazR9ClHek73T8qnK.jpg"
},
{
"id": 73,
"title": "El show de Truman",
"year": "1998",
"runtime": "103",
"genres": ["Comedy","Drama","Sci-Fi"],
"director": "Peter Weir",
"actors": "Jim Carrey, Ed Harris, Laura Linney",
"plot": "Un hombre descubre que toda su vida ha sido transmitida como un reality show.",
"posterUrl": "https://image.tmdb.org/t/p/w500/vuza0WqY239yBXOadKlGwJsZJFE.jpg"
},
{
"id": 74,
"title": "El curioso caso de Benjamin Button",
"year": "2008",
"runtime": "166",
"genres": ["Drama","Fantasy","Romance"],
"director": "David Fincher",
"actors": "Brad Pitt, Cate Blanchett, Tilda Swinton, Julia Ormond",
"plot": "Un hombre nace con el cuerpo de un anciano y rejuvenece con el paso del tiempo mientras vive una historia de amor marcada por el destino.",
"posterUrl": "https://image.tmdb.org/t/p/w500/26wEWZYt6yJkwRVkjcbwJEFh9IS.jpg"
},
{
"id": 75,
"title": "Mad Max: Furia en la carretera",
"year": "2015",
"runtime": "120",
"genres": ["Action","Adventure","Sci-Fi"],
"director": "George Miller",
"actors": "Tom Hardy, Charlize Theron, Nicholas Hoult",
"plot": "En un mundo postapocalíptico, Max ayuda a una mujer rebelde a escapar de un tirano.",
"posterUrl": "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg"
},
{
"id": 76,
"title": "El caballero oscuro: La leyenda renace",
"year": "2012",
"runtime": "164",
"genres": ["Action","Drama","Thriller"],
"director": "Christopher Nolan",
"actors": "Christian Bale, Tom Hardy, Anne Hathaway, Gary Oldman",
"plot": "Batman regresa del exilio para enfrentarse al terrorista Bane.",
"posterUrl": "https://image.tmdb.org/t/p/w500/85cWkCVftiVs0BVey6pxX8uNmLt.jpg"
},
{
"id": 77,
"title": "El sexto sentido",
"year": "1999",
"runtime": "107",
"genres": ["Drama","Mystery","Thriller"],
"director": "M. Night Shyamalan",
"actors": "Bruce Willis, Haley Joel Osment, Toni Collette",
"plot": "Un psicólogo infantil trata a un niño que afirma ver personas muertas.",
"posterUrl": "https://image.tmdb.org/t/p/w500/fIssD3w3SvIhPPmVo4WMgZDVLID.jpg"
},
{
"id": 78,
"title": "El renacido",
"year": "2015",
"runtime": "156",
"genres": ["Adventure","Drama","Thriller"],
"director": "Alejandro G. Iñárritu",
"actors": "Leonardo DiCaprio, Tom Hardy",
"plot": "Un explorador herido lucha por sobrevivir en la naturaleza mientras busca venganza.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BYTgwNmQzZDctMjNmOS00OTExLTkwM2UtNzJmOTJhODFjOTdlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
},
{
"id": 79,
"title": "Parásitos",
"year": "2019",
"runtime": "132",
"genres": ["Drama","Thriller"],
"director": "Bong Joon-ho",
"actors": "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik",
"plot": "Una familia pobre se infiltra en la vida de una familia rica con consecuencias inesperadas.",
"posterUrl": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg"
},
{
"id": 80,
"title": "Joker",
"year": "2019",
"runtime": "122",
"genres": ["Crime","Drama","Thriller"],
"director": "Todd Phillips",
"actors": "Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy",
"plot": "Un comediante fracasado cae en la locura y se convierte en un símbolo del caos.",
"posterUrl": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg"
},
{
"id": 81,
"title": "WALL·E",
"year": "2008",
"runtime": "98",
"genres": ["Animation","Adventure","Family"],
"director": "Andrew Stanton",
"actors": "Ben Burtt, Elissa Knight, Jeff Garlin, Fred Willard",
"plot": "En un futuro lejano, un pequeño robot recolector de basura emprende accidentalmente un viaje espacial que determinará el destino de la humanidad.",
"posterUrl": "https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg"
},
{
"id": 82,
"title": "Perdida",
"year": "2014",
"runtime": "149",
"genres": ["Drama","Mystery","Thriller"],
"director": "David Fincher",
"actors": "Ben Affleck, Rosamund Pike",
"plot": "La desaparición de una mujer expone secretos oscuros en su matrimonio.",
"posterUrl": "https://cdn.kobo.com/book-images/395aef2d-44e2-4f98-bb62-33d7130eabcf/1200/1200/False/gone-girl-movie-tie-in-edition-1.jpg"
},
{
"id": 83,
"title": "Hellboy II: El ejército dorado",
"year": "2008",
"runtime": "120",
"genres": ["Action","Adventure","Fantasy"],
"director": "Guillermo del Toro",
"actors": "Ron Perlman, Selma Blair, Doug Jones, John Hurt",
"plot": "El mundo mítico inicia una rebelión contra la humanidad y Hellboy debe impedir que una antigua armada dorada destruya la Tierra.",
"posterUrl": "https://upload.wikimedia.org/wikipedia/en/5/51/Hellboy_2_poster.jpg"
},
{
"id": 84,
"title": "El crepúsculo de los dioses",
"year": "1950",
"runtime": "110",
"genres": ["Drama","Film-Noir","Romance"],
"director": "Billy Wilder",
"actors": "William Holden, Gloria Swanson, Erich von Stroheim, Nancy Olson",
"plot": "Un guionista en decadencia se ve atrapado en la vida de una antigua estrella del cine mudo obsesionada con su regreso.",
"posterUrl": "https://image.tmdb.org/t/p/w500/9uGHEgsiUXjCNq8wdq4r49YL8A1.jpg"
},
{
"id": 85,
"title": "I-See-You.Com",
"year": "2006",
"runtime": "92",
"genres": ["Comedy"],
"director": "Eric Steven Stahl",
"actors": "Beau Bridges, Rosanna Arquette, Shiri Appleby",
"plot": "Un adolescente monta una web de cámaras ocultas que se convierte en un éxito hasta que todo se descontrola.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BNjBjZjRmYmYtYTJhNC00YTJiLThlODgtZThhNTlmNDZiMjMzXkEyXkFqcGc@._V1_.jpg"
},
{
"id": 86,
"title": "El gran hotel Budapest",
"year": "2014",
"runtime": "99",
"genres": ["Adventure","Comedy","Crime"],
"director": "Wes Anderson",
"actors": "Ralph Fiennes, F. Murray Abraham, Adrien Brody, Willem Dafoe",
"plot": "Las aventuras de un legendario conserje y su joven aprendiz en un hotel europeo entre guerras.",
"posterUrl": "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg"
},
{
"id": 87,
"title": "Guía del autoestopista galáctico",
"year": "2005",
"runtime": "109",
"genres": ["Adventure","Comedy","Sci-Fi"],
"director": "Garth Jennings",
"actors": "Martin Freeman, Zooey Deschanel, Sam Rockwell, Mos Def",
"plot": "Justo antes de que la Tierra sea destruida, Arthur Dent es rescatado por su amigo alienígena y comienza un viaje por el universo.",
"posterUrl": "https://m.media-amazon.com/images/I/8118zkqGKdL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 88,
"title": "Érase una vez en América",
"year": "1984",
"runtime": "229",
"genres": ["Crime","Drama"],
"director": "Sergio Leone",
"actors": "Robert De Niro, James Woods, Elizabeth McGovern, Joe Pesci",
"plot": "Un antiguo gánster regresa a Nueva York décadas después para enfrentarse a su pasado.",
"posterUrl": "https://image.tmdb.org/t/p/w500/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg"
},
{
"id": 89,
"title": "Oblivion",
"year": "2013",
"runtime": "124",
"genres": ["Action","Adventure","Mystery"],
"director": "Joseph Kosinski",
"actors": "Tom Cruise, Morgan Freeman, Olga Kurylenko, Andrea Riseborough",
"plot": "Un técnico encargado de extraer recursos de la Tierra empieza a cuestionar su misión y su realidad.",
"posterUrl": "https://m.media-amazon.com/images/I/71kQAIDUzqL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 90,
"title": "V de Vendetta",
"year": "2005",
"runtime": "132",
"genres": ["Action","Drama","Thriller"],
"director": "James McTeigue",
"actors": "Natalie Portman, Hugo Weaving, Stephen Rea, Stephen Fry",
"plot": "En una dictadura futura, un misterioso justiciero planea derrocar al régimen.",
"posterUrl": "https://m.media-amazon.com/images/I/41QST6DYNDL._AC_UF1000,1000_QL80_.jpg"
},
{
"id": 91,
"title": "Gattaca",
"year": "1997",
"runtime": "106",
"genres": ["Drama","Sci-Fi","Thriller"],
"director": "Andrew Niccol",
"actors": "Ethan Hawke, Uma Thurman, Jude Law, Gore Vidal",
"plot": "Un hombre genéticamente inferior asume otra identidad para cumplir su sueño de viajar al espacio.",
"posterUrl": "https://m.media-amazon.com/images/I/91h1s3T9AYL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 92,
"title": "El lado bueno de las cosas",
"year": "2012",
"runtime": "122",
"genres": ["Comedy","Drama","Romance"],
"director": "David O. Russell",
"actors": "Bradley Cooper, Jennifer Lawrence, Robert De Niro, Jacki Weaver",
"plot": "Un hombre con trastorno bipolar intenta rehacer su vida y conoce a una mujer con sus propios problemas.",
"posterUrl": "https://m.media-amazon.com/images/I/91466Nq7EHL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 93,
"title": "Alicia en el país de las maravillas",
"year": "2010",
"runtime": "108",
"genres": ["Adventure","Family","Fantasy"],
"director": "Tim Burton",
"actors": "Johnny Depp, Mia Wasikowska, Helena Bonham Carter, Anne Hathaway",
"plot": "Alicia regresa al mundo mágico de su infancia para enfrentarse a la Reina Roja.",
"posterUrl": "https://image.tmdb.org/t/p/w500/o0kre9wRCZz3jjSjaru7QU0UtFz.jpg"
},
{
"id": 94,
"title": "Gandhi",
"year": "1982",
"runtime": "191",
"genres": ["Biography","Drama"],
"director": "Richard Attenborough",
"actors": "Ben Kingsley, Candice Bergen, Edward Fox, John Gielgud",
"plot": "La vida de Mahatma Gandhi y su lucha pacífica por la independencia de la India.",
"posterUrl": "https://es.web.img3.acsta.net/pictures/14/04/28/10/33/272881.jpg"
},
{
"id": 95,
"title": "Pacific Rim: Batalla en las profundidades",
"year": "2013",
"runtime": "131",
"genres": ["Action","Adventure","Sci-Fi"],
"director": "Guillermo del Toro",
"actors": "Charlie Hunnam, Idris Elba, Rinko Kikuchi, Charlie Day",
"plot": "Humanos pilotan gigantescos robots para combatir monstruos que emergen del océano.",
"posterUrl": "https://image.tmdb.org/t/p/w500/mmznhaQDwlHWpUwKuNxtQiubbmM.jpg"
},
{
"id": 96,
"title": "Kiss Kiss Bang Bang",
"year": "2005",
"runtime": "103",
"genres": ["Comedy","Crime","Mystery"],
"director": "Shane Black",
"actors": "Robert Downey Jr., Val Kilmer, Michelle Monaghan, Corbin Bernsen",
"plot": "Un ladrón se ve envuelto en un asesinato mientras intenta convertirse en actor en Hollywood.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BMTY5NDExMDA3M15BMl5BanBnXkFtZTYwNTc2MzA3._V1_.jpg"
},
{
"id": 97,
"title": "El americano tranquilo",
"year": "2002",
"runtime": "101",
"genres": ["Drama","Mystery","Romance"],
"director": "Phillip Noyce",
"actors": "Michael Caine, Brendan Fraser, Do Thi Hai Yen",
"plot": "Un periodista británico y un joven estadounidense compiten por el amor de una mujer vietnamita.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BYmYxYjk5OTMtNjlmNy00ODI4LTgyMTMtNmY0NjdlODdlZDhlXkEyXkFqcGc@._V1_.jpg"
},
{
"id": 98,
"title": "El atlas de las nubes",
"year": "2012",
"runtime": "172",
"genres": ["Drama","Sci-Fi"],
"director": "Tom Tykwer, Lana Wachowski, Lilly Wachowski",
"actors": "Tom Hanks, Halle Berry, Jim Broadbent, Hugo Weaving",
"plot": "Historias entrelazadas muestran cómo las acciones individuales afectan el pasado, presente y futuro.",
"posterUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSamqRqvhLXy00COWmXFAaOjWoRqQyuNX0Lbg&s"
},
{
"id": 99,
"title": "Lo imposible",
"year": "2012",
"runtime": "114",
"genres": ["Drama","Thriller"],
"director": "J.A. Bayona",
"actors": "Naomi Watts, Ewan McGregor, Tom Holland",
"plot": "Una familia atrapada en el tsunami del océano Índico lucha por sobrevivir.",
"posterUrl": "https://m.media-amazon.com/images/I/81wrDB9c4BL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 100,
"title": "Sin novedad en el frente",
"year": "1930",
"runtime": "136",
"genres": ["Drama","War"],
"director": "Lewis Milestone",
"actors": "Lew Ayres, Louis Wolheim, John Wray",
"plot": "Un joven soldado alemán experimenta el horror y la desilusión de la Primera Guerra Mundial.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BOWJiYWMyYTktZThhOS00ZjgxLWE0YTQtZDMyNTQxMjMyYjI2XkEyXkFqcGc@._V1_.jpg"
},
{
"id": 101,
"title": "El paciente inglés",
"year": "1996",
"runtime": "162",
"genres": ["Drama","Romance","War"],
"director": "Anthony Minghella",
"actors": "Ralph Fiennes, Juliette Binoche, Willem Dafoe, Kristin Scott Thomas",
"plot": "Al final de la Segunda Guerra Mundial, una enfermera cuida a un paciente gravemente quemado cuya historia se revela a través de recuerdos de un amor prohibido.",
"posterUrl": "https://image.tmdb.org/t/p/w500/7c9UVPPiTPltouxRVY6N9uugaVA.jpg"
},
{
"id": 102,
"title": "Dallas Buyers Club",
"year": "2013",
"runtime": "117",
"genres": ["Biography","Drama"],
"director": "Jean-Marc Vallée",
"actors": "Matthew McConaughey, Jennifer Garner, Jared Leto, Denis O'Hare",
"plot": "Un electricista diagnosticado con VIH desafía al sistema médico para conseguir tratamientos alternativos.",
"posterUrl": "https://m.media-amazon.com/images/I/91jUjz9+sNL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 103,
"title": "Frida",
"year": "2002",
"runtime": "123",
"genres": ["Biography","Drama","Romance"],
"director": "Julie Taymor",
"actors": "Salma Hayek, Alfred Molina, Geoffrey Rush, Antonio Banderas",
"plot": "La vida de la pintora Frida Kahlo y cómo transformó su dolor y su relación con Diego Rivera en arte.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BNTU1OWViNjAtMjc1NS00YTQzLTk5ZTQtYTM5Y2EwNTlmNGEyXkEyXkFqcGc@._V1_.jpg"
},
{
"id": 104,
"title": "Antes del amanecer",
"year": "1995",
"runtime": "105",
"genres": ["Drama","Romance"],
"director": "Richard Linklater",
"actors": "Ethan Hawke, Julie Delpy",
"plot": "Un joven estadounidense y una francesa se conocen en un tren y pasan una noche inolvidable en Viena.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BZDZhZmI1ZTUtYWI3NC00NTMwLTk3NWMtNDc0OGNjM2I0ZjlmXkEyXkFqcGc@._V1_.jpg"
},
{
"id": 105,
"title": "El diario del ron",
"year": "2011",
"runtime": "120",
"genres": ["Comedy","Drama"],
"director": "Bruce Robinson",
"actors": "Johnny Depp, Aaron Eckhart, Amber Heard, Michael Rispoli",
"plot": "Un periodista estadounidense se muda a Puerto Rico en los años 60 y se ve envuelto en intrigas y corrupción.",
"posterUrl": "https://m.media-amazon.com/images/I/81YX+Rs2rFL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 106,
"title": "El último samurái",
"year": "2003",
"runtime": "154",
"genres": ["Action","Drama","History"],
"director": "Edward Zwick",
"actors": "Tom Cruise, Ken Watanabe, Timothy Spall",
"plot": "Un militar estadounidense adopta la cultura samurái tras ser capturado en Japón.",
"posterUrl": "https://m.media-amazon.com/images/I/716oQG+qjUL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 107,
"title": "Chinatown",
"year": "1974",
"runtime": "130",
"genres": ["Drama","Mystery","Thriller"],
"director": "Roman Polanski",
"actors": "Jack Nicholson, Faye Dunaway, John Huston",
"plot": "Un detective privado descubre una compleja trama de corrupción y asesinato en Los Ángeles.",
"posterUrl": "https://alquimicos.com/wp-content/uploads/2023/12/Chinatown.jpg"
},
{
"id": 108,
"title": "Calvario",
"year": "2014",
"runtime": "102",
"genres": ["Comedy","Drama"],
"director": "John Michael McDonagh",
"actors": "Brendan Gleeson, Chris O'Dowd, Kelly Reilly",
"plot": "Un sacerdote recibe una amenaza de muerte y reflexiona sobre su fe y su comunidad.",
"posterUrl": "https://es.web.img3.acsta.net/pictures/14/10/28/13/22/480440.jpg"
},
{
"id": 109,
"title": "Antes del atardecer",
"year": "2004",
"runtime": "80",
"genres": ["Drama","Romance"],
"director": "Richard Linklater",
"actors": "Ethan Hawke, Julie Delpy",
"plot": "Nueve años después de su primer encuentro, Jesse y Celine se reencuentran en París.",
"posterUrl": "https://play-lh.googleusercontent.com/nwVFHRR_B0X2Wr8pWPWzb3XsPHph_3_SIjSJU2lM7ykqxZAhap5mT0mJIluRzfuTjboP"
},
{
"id": 110,
"title": "El viaje de Chihiro",
"year": "2001",
"runtime": "125",
"genres": ["Animation","Adventure","Family"],
"director": "Hayao Miyazaki",
"actors": "Rumi Hiiragi, Miyu Irino",
"plot": "Una niña entra en un mundo de espíritus y debe trabajar para salvar a sus padres.",
"posterUrl": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg"
},
{
"id": 111,
"title": "Indochina",
"year": "1992",
"runtime": "159",
"genres": ["Drama","Romance"],
"director": "Régis Wargnier",
"actors": "Catherine Deneuve, Vincent Pérez",
"plot": "En la Indochina colonial, una mujer francesa cría a una princesa vietnamita en tiempos de conflicto.",
"posterUrl": "https://pics.filmaffinity.com/Indochina-566910177-large.jpg"
},
{
"id": 112,
"title": "Birdman",
"year": "2014",
"runtime": "119",
"genres": ["Comedy","Drama"],
"director": "Alejandro G. Iñárritu",
"actors": "Michael Keaton, Emma Stone, Edward Norton",
"plot": "Un actor en decadencia intenta recuperar su prestigio montando una obra en Broadway.",
"posterUrl": "https://m.media-amazon.com/images/I/91oJ7cYnH+L._AC_UF894,1000_QL80_.jpg"
},
{
"id": 113,
"title": "Boyhood",
"year": "2014",
"runtime": "165",
"genres": ["Drama"],
"director": "Richard Linklater",
"actors": "Ellar Coltrane, Patricia Arquette, Ethan Hawke",
"plot": "La vida de un niño desde la infancia hasta su llegada a la universidad.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BMTYzNDc2MDc0N15BMl5BanBnXkFtZTgwOTcwMDQ5MTE@._V1_FMjpg_UX1000_.jpg"
},
{
"id": 114,
"title": "12 hombres sin piedad",
"year": "1957",
"runtime": "96",
"genres": ["Crime","Drama"],
"director": "Sidney Lumet",
"actors": "Henry Fonda, Lee J. Cobb, Martin Balsam",
"plot": "Un jurado intenta evitar una injusticia forzando a sus compañeros a reconsiderar las pruebas.",
"posterUrl": "https://image.tmdb.org/t/p/w500/7sf9CgJz30aXDvrg7DYYUQ2U91T.jpg"
},
{
"id": 115,
"title": "El código Enigma",
"year": "2014",
"runtime": "114",
"genres": ["Biography","Drama","Thriller"],
"director": "Morten Tyldum",
"actors": "Benedict Cumberbatch, Keira Knightley, Matthew Goode",
"plot": "Alan Turing intenta descifrar el código Enigma durante la Segunda Guerra Mundial.",
"posterUrl": "https://m.media-amazon.com/images/I/81Zc1Xgz7zL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 116,
"title": "1917",
"year": "2019",
"runtime": "119",
"genres": ["Drama","War"],
"director": "Sam Mendes",
"actors": "George MacKay, Dean-Charles Chapman",
"plot": "Dos soldados británicos reciben una misión urgente durante la Primera Guerra Mundial.",
"posterUrl": "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg"
},
{
"id": 117,
"title": "Big Nothing",
"year": "2006",
"runtime": "86",
"genres": ["Comedy","Crime","Thriller"],
"director": "Jean-Baptiste Andrea",
"actors": "David Schwimmer, Simon Pegg, Alice Eve",
"plot": "Un profesor desempleado se une a un estafador en un plan de chantaje que se complica.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BY2FhOGQzZTItMTdmOC00ZGI0LWFjZjMtYWQ1ZTNhNWFlMjE5XkEyXkFqcGc@._V1_.jpg"
},
{
"id": 118,
"title": "El submarino",
"year": "1981",
"runtime": "149",
"genres": ["Adventure","Drama","Thriller"],
"director": "Wolfgang Petersen",
"actors": "Jürgen Prochnow, Herbert Grönemeyer",
"plot": "La claustrofóbica experiencia de la tripulación de un submarino alemán en la Segunda Guerra Mundial.",
"posterUrl": "https://m.media-amazon.com/images/I/817gNvOGd8L._AC_UF894,1000_QL80_.jpg"
},
{
"id": 119,
"title": "Shrek 2",
"year": "2004",
"runtime": "93",
"genres": ["Animation","Adventure","Comedy"],
"director": "Andrew Adamson",
"actors": "Mike Myers, Eddie Murphy, Cameron Diaz",
"plot": "Shrek y Fiona visitan a los padres de ella, quienes desconocen que su hija es una ogra.",
"posterUrl": "https://image.tmdb.org/t/p/w500/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg"
},
{
"id": 120,
"title": "Sin City: La ciudad del pecado",
"year": "2005",
"runtime": "124",
"genres": ["Crime","Thriller"],
"director": "Frank Miller, Robert Rodriguez",
"actors": "Jessica Alba, Mickey Rourke, Clive Owen",
"plot": "Varias historias de violencia y corrupción se cruzan en la ciudad de Basin City.",
"posterUrl": "https://m.media-amazon.com/images/I/71XEPUiY8LL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 121,
"title": "Nebraska",
"year": "2013",
"runtime": "115",
"genres": ["Adventure","Comedy","Drama"],
"director": "Alexander Payne",
"actors": "Bruce Dern, Will Forte, June Squibb, Bob Odenkirk",
"plot": "Un padre anciano y alcohólico viaja con su hijo desde Montana hasta Nebraska para reclamar un supuesto premio millonario.",
"posterUrl": "https://es.web.img2.acsta.net/pictures/13/12/30/17/19/261276.jpg"
},
{
"id": 122,
"title": "Shrek",
"year": "2001",
"runtime": "90",
"genres": ["Animation","Adventure","Comedy"],
"director": "Andrew Adamson, Vicky Jenson",
"actors": "Mike Myers, Eddie Murphy, Cameron Diaz, John Lithgow",
"plot": "Un ogro solitario acepta rescatar a una princesa para recuperar la tranquilidad de su pantano.",
"posterUrl": "https://image.tmdb.org/t/p/w500/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg"
},
{
"id": 123,
"title": "Sr. y Sra. Smith",
"year": "2005",
"runtime": "120",
"genres": ["Action","Comedy","Crime"],
"director": "Doug Liman",
"actors": "Brad Pitt, Angelina Jolie, Vince Vaughn, Adam Brody",
"plot": "Un matrimonio aburrido descubre que ambos son asesinos a sueldo contratados para eliminarse mutuamente.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BMTUxMzcxNzQzOF5BMl5BanBnXkFtZTcwMzQxNjUyMw@@._V1_.jpg"
},
{
"id": 124,
"title": "Pecado original",
"year": "2001",
"runtime": "116",
"genres": ["Drama","Mystery","Romance"],
"director": "Michael Cristofer",
"actors": "Antonio Banderas, Angelina Jolie, Thomas Jane, Jack Thompson",
"plot": "Una mujer planea estafar a un hombre rico tras casarse con él, pero las emociones complican el plan.",
"posterUrl": "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Original_sin_poster.jpg/250px-Original_sin_poster.jpg"
},
{
"id": 125,
"title": "Shrek para siempre",
"year": "2010",
"runtime": "93",
"genres": ["Animation","Adventure","Comedy"],
"director": "Mike Mitchell",
"actors": "Mike Myers, Eddie Murphy, Cameron Diaz, Antonio Banderas",
"plot": "Shrek firma un trato que altera la realidad y debe restaurar su mundo antes de perderlo todo.",
"posterUrl": "https://m.media-amazon.com/images/I/8148AAppyOL.jpg"
},
{
"id": 126,
"title": "Antes de medianoche",
"year": "2013",
"runtime": "109",
"genres": ["Drama","Romance"],
"director": "Richard Linklater",
"actors": "Ethan Hawke, Julie Delpy, Seamus Davey-Fitzpatrick",
"plot": "Jesse y Celine enfrentan las complejidades del amor muchos años después de su primer encuentro.",
"posterUrl": "https://m.media-amazon.com/images/I/91j08eQFyCL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 127,
"title": "Gru, mi villano favorito",
"year": "2010",
"runtime": "95",
"genres": ["Animation","Adventure","Comedy"],
"director": "Pierre Coffin, Chris Renaud",
"actors": "Steve Carell, Jason Segel, Russell Brand, Julie Andrews",
"plot": "Un villano planea robar la Luna, pero la llegada de tres niñas cambia su vida.",
"posterUrl": "https://upload.wikimedia.org/wikipedia/en/c/c0/Despicable_Me_%282010_animated_feature_film%29.jpg"
},
{
"id": 128,
"title": "Troya",
"year": "2004",
"runtime": "163",
"genres": ["Adventure"],
"director": "Wolfgang Petersen",
"actors": "Brad Pitt, Eric Bana, Orlando Bloom, Diane Kruger",
"plot": "La legendaria guerra de Troya se desata tras el secuestro de Helena.",
"posterUrl": "https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Troy_03500296.png/250px-Troy_03500296.png"
},
{
"id": 129,
"title": "El hobbit: Un viaje inesperado",
"year": "2012",
"runtime": "169",
"genres": ["Adventure","Fantasy"],
"director": "Peter Jackson",
"actors": "Martin Freeman, Ian McKellen, Richard Armitage",
"plot": "Bilbo Bolsón se embarca en una aventura para recuperar el reino enano de Erebor.",
"posterUrl": "https://image.tmdb.org/t/p/w500/yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg"
},
{
"id": 130,
"title": "El gran Gatsby",
"year": "2013",
"runtime": "143",
"genres": ["Drama","Romance"],
"director": "Baz Luhrmann",
"actors": "Leonardo DiCaprio, Carey Mulligan, Tobey Maguire",
"plot": "Un escritor se ve atrapado en el extravagante mundo del millonario Jay Gatsby.",
"posterUrl": "https://upload.wikimedia.org/wikipedia/en/c/c2/TheGreatGatsby2013Poster.jpg"
},
{
"id": 131,
"title": "La era del hielo",
"year": "2002",
"runtime": "81",
"genres": ["Animation","Adventure","Comedy"],
"director": "Chris Wedge",
"actors": "Ray Romano, John Leguizamo, Denis Leary",
"plot": "Un mamut, un perezoso y un tigre dientes de sable ayudan a un bebé humano a regresar con su tribu.",
"posterUrl": "https://image.tmdb.org/t/p/w500/zpaQwR0YViPd83bx1e559QyZ35i.jpg"
},
{
"id": 132,
"title": "El irlandés",
"year": "2019",
"runtime": "209",
"genres": ["Crime","Drama"],
"director": "Martin Scorsese",
"actors": "Robert De Niro, Al Pacino, Joe Pesci",
"plot": "Un veterano asesino a sueldo recuerda su implicación en la desaparición de Jimmy Hoffa.",
"posterUrl": "https://image.tmdb.org/t/p/w500/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg"
},
{
"id": 133,
"title": "El curioso caso de Benjamin Button",
"year": "2008",
"runtime": "166",
"genres": ["Drama","Fantasy","Romance"],
"director": "David Fincher",
"actors": "Brad Pitt, Cate Blanchett, Tilda Swinton",
"plot": "Un hombre nace con el cuerpo de un anciano y rejuvenece con el paso del tiempo mientras vive una historia marcada por el amor y el destino.",
"posterUrl": "https://image.tmdb.org/t/p/w500/26wEWZYt6yJkwRVkjcbwJEFh9IS.jpg"
},
{
"id": 134,
"title": "Ex Machina",
"year": "2015",
"runtime": "108",
"genres": ["Drama","Mystery","Sci-Fi"],
"director": "Alex Garland",
"actors": "Domhnall Gleeson, Alicia Vikander, Oscar Isaac",
"plot": "Un programador evalúa la conciencia de una avanzada inteligencia artificial.",
"posterUrl": "https://m.media-amazon.com/images/M/MV5BMTUxNzc0OTIxMV5BMl5BanBnXkFtZTgwNDI3NzU2NDE@._V1_FMjpg_UX1000_.jpg"
},
{
"id": 135,
"title": "La teoría del todo",
"year": "2014",
"runtime": "123",
"genres": ["Biography","Drama","Romance"],
"director": "James Marsh",
"actors": "Eddie Redmayne, Felicity Jones",
"plot": "La relación entre Stephen Hawking y su primera esposa mientras él lucha contra la enfermedad.",
"posterUrl": "https://upload.wikimedia.org/wikipedia/en/6/67/The_Theory_of_Everything_%282014%29.jpg"
},
{
"id": 136,
"title": "Shogun",
"year": "1980",
"runtime": "60",
"genres": ["Adventure","Drama","History"],
"director": "Jerry London",
"actors": "Richard Chamberlain, Toshirô Mifune",
"plot": "Un navegante inglés se ve envuelto en intrigas políticas en el Japón feudal.",
"posterUrl": "https://m.media-amazon.com/images/I/81b-E1jf9kL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 137,
"title": "Spotlight",
"year": "2015",
"runtime": "128",
"genres": ["Biography","Crime","Drama"],
"director": "Tom McCarthy",
"actors": "Mark Ruffalo, Michael Keaton, Rachel McAdams",
"plot": "El equipo Spotlight del Boston Globe destapa un escándalo de abusos en la Iglesia.",
"posterUrl": "https://m.media-amazon.com/images/I/91Zy18In8IL._AC_UF1000,1000_QL80_.jpg"
},
{
"id": 138,
"title": "Vértigo",
"year": "1958",
"runtime": "128",
"genres": ["Mystery","Romance","Thriller"],
"director": "Alfred Hitchcock",
"actors": "James Stewart, Kim Novak",
"plot": "Un detective con acrofobia se obsesiona con una mujer a la que debe vigilar.",
"posterUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdbG3WYxoLebNsTjC5DNCfmwdwIAg_DsHHsA&s"
},
{
"id": 139,
"title": "Hijos de los hombres",
"year": "2006",
"runtime": "109",
"genres": ["Drama","Sci-Fi","Thriller"],
"director": "Alfonso Cuarón",
"actors": "Clive Owen, Julianne Moore, Michael Caine",
"plot": "En un futuro donde la humanidad ha perdido la capacidad de reproducirse, un hombre debe proteger a la única mujer embarazada del planeta.",
"posterUrl": "https://mediaproxy.tvtropes.org/width/1200/https://static.tvtropes.org/pmwiki/pub/images/img_2902_41.jpeg"
},
{
"id": 140,
"title": "La vida de los otros",
"year": "2006",
"runtime": "137",
"genres": ["Drama","Thriller"],
"director": "Florian Henckel von Donnersmarck",
"actors": "Ulrich Mühe, Martina Gedeck",
"plot": "Un agente de la Stasi comienza a cuestionar el régimen mientras espía a una pareja.",
"posterUrl": "https://m.media-amazon.com/images/I/613dY5sEQrL._AC_UF1000,1000_QL80_.jpg"
},
{
"id": 141,
"title": "Hotel Ruanda",
"year": "2004",
"runtime": "121",
"genres": ["Drama","History","War"],
"director": "Terry George",
"actors": "Don Cheadle, Sophie Okonedo",
"plot": "Un gerente de hotel protege a cientos de refugiados durante el genocidio en Ruanda.",
"posterUrl": "https://m.media-amazon.com/images/I/713J58BbhnL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 142,
"title": "Misión rescate",
"year": "2015",
"runtime": "144",
"genres": ["Adventure","Drama","Sci-Fi"],
"director": "Ridley Scott",
"actors": "Matt Damon, Jessica Chastain",
"plot": "Un astronauta queda atrapado en Marte y lucha por sobrevivir hasta ser rescatado.",
"posterUrl": "https://es.web.img3.acsta.net/pictures/15/08/27/13/26/081921.jpg"
},
{
"id": 143,
"title": "Matar a un ruiseñor",
"year": "1962",
"runtime": "129",
"genres": ["Crime","Drama"],
"director": "Robert Mulligan",
"actors": "Gregory Peck, Mary Badham",
"plot": "Un abogado defiende a un hombre negro acusado injustamente en el sur de EE.UU.",
"posterUrl": "https://play-lh.googleusercontent.com/YFjwVyUQzQN75eK4zO7QUEd9njzP5Gyt2PF0WKpvjZmQV3RRxhzzaiVC-wfV5gAboU8N"
},
{
"id": 144,
"title": "Los ocho más odiados",
"year": "2015",
"runtime": "187",
"genres": ["Crime","Drama","Mystery"],
"director": "Quentin Tarantino",
"actors": "Samuel L. Jackson, Kurt Russell, Jennifer Jason Leigh",
"plot": "Un grupo de desconocidos queda atrapado en una cabaña durante una tormenta de nieve.",
"posterUrl": "https://image.tmdb.org/t/p/w500/jIywvdPjia2t3eKYbjVTcwBQlG8.jpg"
},
{
"id": 145,
"title": "Una separación",
"year": "2011",
"runtime": "123",
"genres": ["Drama","Mystery"],
"director": "Asghar Farhadi",
"actors": "Leila Hatami, Peyman Moaadi",
"plot": "Una pareja iraní enfrenta un conflicto legal y moral tras decidir separarse.",
"posterUrl": "https://m.media-amazon.com/images/I/81+QxcWwiGL.jpg"
},
{
"id": 146,
"title": "La gran apuesta",
"year": "2015",
"runtime": "130",
"genres": ["Biography","Comedy","Drama"],
"director": "Adam McKay",
"actors": "Christian Bale, Steve Carell, Ryan Gosling",
"plot": "Un grupo de inversores predice la crisis financiera de 2008 y apuesta contra el sistema.",
"posterUrl": "https://m.media-amazon.com/images/I/71g5cBwy9PL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 147,
"title": "Al filo del mañana",
"year": "2014",
"runtime": "113",
"genres": ["Action","Sci-Fi"],
"director": "Doug Liman",
"actors": "Tom Cruise, Emily Blunt, Bill Paxton",
"plot": "Un oficial militar revive el mismo día una y otra vez mientras lucha contra una invasión alienígena.",
"posterUrl": "https://image.tmdb.org/t/p/w500/uUHvlkLavotfGsNtosDy8ShsIYF.jpg"
},
{
"id": 148,
"title": "Prisioneros",
"year": "2013",
"runtime": "153",
"genres": ["Crime","Drama","Thriller"],
"director": "Denis Villeneuve",
"actors": "Hugh Jackman, Jake Gyllenhaal, Viola Davis",
"plot": "Cuando su hija desaparece, un padre desesperado toma medidas extremas mientras la policía investiga.",
"posterUrl": "https://image.tmdb.org/t/p/w500/tuZhZ6biFMr5n9YSVuHOJnNL1uU.jpg"
},
{
"id": 149,
"title": "Drive",
"year": "2011",
"runtime": "100",
"genres": ["Crime","Drama","Thriller"],
"director": "Nicolas Winding Refn",
"actors": "Ryan Gosling, Carey Mulligan, Bryan Cranston",
"plot": "Un conductor especializado en fugas se ve envuelto en una peligrosa conspiración criminal.",
"posterUrl": "https://image.tmdb.org/t/p/w500/602vevIURmpDfzbnv5Ubi6wIkQm.jpg"
},
{
"id": 150,
"title": "Ella",
"year": "2013",
"runtime": "126",
"genres": ["Drama","Romance","Sci-Fi"],
"director": "Spike Jonze",
"actors": "Joaquin Phoenix, Scarlett Johansson, Amy Adams",
"plot": "Un hombre solitario desarrolla una relación emocional con un avanzado sistema operativo con inteligencia artificial.",
"posterUrl": "https://image.tmdb.org/t/p/w500/yk4J4aewWYNiBhD49WD7UaBBn37.jpg"
}
]